name: Book Build for Amazon KDP

on:
 workflow_dispatch: # Manual triggering
 push:
 branches: [ main ] # Automatic triggering on push to main branch
 paths-ignore:
 - 'agents/**'

# Set permissions for the workflow
permissions:
 contents: write # Needed for creating releases

jobs:
 # Job 1: Set up the environment and build the book files
 build-book:
 name: Build Book PDF
 runs-on: ubuntu-latest
 outputs:
 pdf_path: ${{ steps.build-pdf.outputs.pdf_path }}
 build_success: ${{ steps.build-pdf.outputs.build_success }}
 steps:
 - name: Checkout repository
 uses: actions/checkout@v4
 
 - name: Set up environment
 run: |
 sudo apt-get update
 sudo apt-get install -y asciidoctor
 sudo gem install asciidoctor-pdf
 asciidoctor --version
 
 - name: Build PDF
 id: build-pdf
 run: |
 # Detailed PDF build process with error handling and artifact generation
 
 # Job 2: Create the GitHub release with the built files
 create-release:
 name: Create GitHub Release
 needs: build-book
 runs-on: ubuntu-latest
 steps:
 # Checkout, rebuild PDF, generate release with CLI